version: "3.7"
services:
        front:
                image: ${AMTN_FRONT_IMAGE}
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - type: bind
                          source: ${AMTN_FRONT_CERTDIR_IN_HOST}
                          target: /etc/letsencrypt
                environment:
                        - CERTBOT_EMAIL=${AMTN_CERTBOT_EMAIL}

        worker:
                image: ${AMTN_WORKER_IMAGE}
                command: --prefix=/worker/8080
                ports:
                        - "8080:8080"
                volumes:
                        - type: bind
                          source: ${AMTN_WORKER_WORKDIR}
                          target: ${AMTN_WORKER_WORKDIR}
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
                        - type: bind
                          source: ${HOME}/.docker/machine
                          target: /root/.docker/machine
                        - type: bind
                          source: ${AMTN_FRONT_CERTDIR_IN_HOST}
                          target: /etc/letsencrypt
                environment:
                        - JENKINS_HOME=${AMTN_WORKER_WORKDIR}



