version: "3.7"
services:
        front:
                image: santaent/front
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - type: bind
                          source: /etc/letsencrypt
                          target: /etc/letsencrypt
                environment:
                        - CERTBOT_EMAIL=${AMTN_CERTBOT_EMAIL}

        worker:
                image: santaent/worker
                command: --prefix=/worker/8080
                ports:
                        - "8080:8080"
                volumes:
                        - type: bind
                          source: /var/jenkins_home
                          target: /var/jenkins_home
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
                        - type: bind
                          source: ${HOME}/.docker/machine
                          target: /root/.docker/machine
                        - type: bind
                          source: /etc/letsencrypt
                          target: /etc/letsencrypt



