# fix version in case of the image polluted by attacker
# if you want to update, please check its safety manually
FROM staticfloat/nginx-certbot@sha256:77c988aca00213cc2818af5f617cc9ae7672bc398fc76ac7d6192b75978d5386
COPY config/*.conf /etc/nginx/conf.d/
